HoardSorter/HoardSorter/Models/CardCollection.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HoardSorter.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.Linq;

    public partial class CardCollection
    {
        public int CardCollectionID { get; set; }
        public int CardID { get; set; }
        [Display(Name = "Trade")]
        public Nullable<bool> ToTrade { get; set; }
        [Display(Name = "Want")]
        public Nullable<bool> Wanted { get; set; }
        [Display(Name = "Owned Qty")]
        public Nullable<int> OwnedQty { get; set; }
        [Display(Name = "Trade Qty")]
        public Nullable<int> TradeQty { get; set; }
        [Display(Name = "Want Qty")]
        public Nullable<int> WantQty { get; set; }
        public int collectorID { get; set; }
    
        public virtual CardDetails CardDetails { get; set; }
        public virtual Collections Collections { get; set; }

        public virtual IEnumerable<int> DupCards
        {
            get
            {
                IEnumerable<int> thecards;
                using (var db = new HoardSorterEntities())
                {
                    var thecards1 = db.CardCollection.Where(ri => ri.collectorID == collectorID).ToList();
                    thecards = thecards1.Select(x => x.CardID);
                }
                return thecards;
            }
        }
    }
}

HoardSorter/HoardSorter/Controllers/CardCollectionsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using HoardSorter.Models;

namespace HoardSorter.Controllers
{
    public class CardCollectionsController : Controller
    {
        private HoardSorterEntities db = new HoardSorterEntities();
        public int test;
        // GET: CardCollections
        public ActionResult Index(string sortOrder)
        {
            String id = (db.AspNetUsers.Where(x => x.Email == System.Web.HttpContext.Current.User.Identity.Name).FirstOrDefault().Id);
            var collectorID = db.Collections.Where(y => y.UserID == id).FirstOrDefault().collectorID;

            var cardCollection = db.CardCollection.Where(c => c.collectorID == collectorID);
            ViewBag.NameSortParm = String.IsNullOrEmpty(sortOrder) ? "name_desc" : "";
            ViewBag.CostSortParm = sortOrder == "cost_asc" ? "cost_desc" : "cost_asc";
            ViewBag.QtySortParm = sortOrder == "qty_asc" ? "qty_desc" : "qty_asc";
            ViewBag.NameLabel = String.IsNullOrEmpty(sortOrder) ? "Name Z-A" : "Name A-Z";
            ViewBag.CostLabel = sortOrder == "cost_asc" ? "Cost v" : "Cost ^";
            ViewBag.QuantityLabel = sortOrder == "qty_asc" ? "Quantity v" : "Quantity ^";
            switch (sortOrder)
            {
                case "name_desc":
                    cardCollection = cardCollection.OrderByDescending(s => s.CardDetails.CardName);
                    break;
                case "cost_desc":
                    cardCollection = cardCollection.OrderByDescending(s => s.CardDetails.ConvertedManaCost);
                    break;
                case "cost_asc":
                    cardCollection = cardCollection.OrderBy(s => s.CardDetails.ConvertedManaCost);
                    break;
                case "qty_desc":
                    cardCollection = cardCollection.OrderByDescending(s => s.OwnedQty);
                    break;
                case "qty_asc":
                    cardCollection = cardCollection.OrderBy(s => s.OwnedQty);
                    break;
                default:
                    cardCollection = cardCollection.OrderBy(s => s.CardDetails.CardName);
                    break;
            }


            return View(cardCollection.ToList());
        }

        public ActionResult CreateTrade()
        {
            String id = (db.AspNetUsers.Where(x => x.Email == System.Web.HttpContext.Current.User.Identity.Name).FirstOrDefault().Id);
            var collectorID = db.Collections.Where(y => y.UserID == id).FirstOrDefault().collectorID;

            var cardCollection = db.CardCollection.Where(c => c.collectorID == collectorID);
            cardCollection = cardCollection.OrderBy(s => s.CardDetails.CardName);
            return View(cardCollection.ToList());
        }


        public ActionResult MyTrades()
        {
            String id = (db.AspNetUsers.Where(x => x.Email == System.Web.HttpContext.Current.User.Identity.Name).FirstOrDefault().Id);
            var collectorID = db.Collections.Where(y => y.UserID == id).FirstOrDefault().collectorID;

            var cardCollection = db.CardCollection.Where(c => c.collectorID == collectorID);
            cardCollection = cardCollection.OrderBy(s => s.CardDetails.CardName);
            return View(cardCollection.ToList());
        }

        public ActionResult FriendView(String id)
        {
            var collectorID = db.Collections.Where(y => y.UserID == id.ToString()).FirstOrDefault().collectorID;

            String email = (db.AspNetUsers.Where(x => x.Id == id).FirstOrDefault().Email);
            ViewBag.Friend = email;

            var cardCollection = db.CardCollection.Where(c => c.collectorID == collectorID);
            return View(cardCollection.ToList());
        }

        public ActionResult Search()
        {
            ViewBag.CardID = new SelectList(db.CardDetails.OrderBy(s => s.CardName), "CardID", "CardName");
            ViewBag.collectorID = new SelectList(db.Collections, "collectorID", "UserID");
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Search(int CardID)
        {
            return RedirectToAction("SearchResults", new { id = CardID });

        }

        public ActionResult SearchResults(int id)
        {
            var cardCollection = db.CardCollection.Where(c => c.CardID == id).OrderBy(y => y.Collections.AspNetUsers.Email);

            return View(cardCollection);
        }


        public ActionResult MyWants()
        {
            String id = (db.AspNetUsers.Where(x => x.Email == System.Web.HttpContext.Current.User.Identity.Name).FirstOrDefault().Id);
            var collectorID = db.Collections.Where(y => y.UserID == id).FirstOrDefault().collectorID;

            var cardCollection = db.CardCollection.Where(c => c.collectorID == collectorID);
            cardCollection = cardCollection.OrderBy(s => s.CardDetails.CardName);
            return View(cardCollection.ToList());
        }

        // GET: CardCollections/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            CardCollection cardCollection = db.CardCollection.Find(id);
            if (cardCollection == null)
            {
                return HttpNotFound();
            }
            return View(cardCollection);
        }

        // GET: CardCollections/Create
        public ActionResult Create()
        {
            ViewBag.CardID = new SelectList(db.CardDetails.OrderBy(s => s.CardName), "CardID", "CardName");
            ViewBag.collectorID = new SelectList(db.Collections, "collectorID", "UserID");
            return View();
        }

        public ActionResult CreateWant()
        {
            ViewBag.CardID = new SelectList(db.CardDetails.OrderBy(s => s.CardName), "CardID", "CardName");
            ViewBag.collectorID = new SelectList(db.Collections, "collectorID", "UserID");
            return View();
        }

        // POST: CardCollections/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "CardCollectionID,CardID,ToTrade,Wanted,OwnedQty,TradeQty,WantQty,collectorID")] CardCollection cardCollection)
        {
            

            if (ModelState.IsValid)
            {
                String id = (db.AspNetUsers.Where(x => x.Email == System.Web.HttpContext.Current.User.Identity.Name).FirstOrDefault().Id);
                cardCollection.collectorID = db.Collections.Where(y => y.UserID == id).FirstOrDefault().collectorID;
                db.CardCollection.Add(cardCollection);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.Error = "Error: Duplicate card in collection!";

            ViewBag.CardID = new SelectList(db.CardDetails, "CardID", "CardName", cardCollection.CardID);
            ViewBag.collectorID = new SelectList(db.Collections, "collectorID", "UserID", cardCollection.collectorID);
            return View(cardCollection);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult CreateWant([Bind(Include = "CardCollectionID,CardID,ToTrade,Wanted,OwnedQty,TradeQty,WantQty,collectorID")] CardCollection cardCollection)
        {

            if (ModelState.IsValid)
            {
                String id = (db.AspNetUsers.Where(x => x.Email == System.Web.HttpContext.Current.User.Identity.Name).FirstOrDefault().Id);
                cardCollection.collectorID = db.Collections.Where(y => y.UserID == id).FirstOrDefault().collectorID;
                db.CardCollection.Add(cardCollection);
                db.SaveChanges();
                return RedirectToAction("MyWants");
            }


            ViewBag.CardID = new SelectList(db.CardDetails, "CardID", "CardName", cardCollection.CardID);
            ViewBag.collectorID = new SelectList(db.Collections, "collectorID", "UserID", cardCollection.collectorID);
            return View(cardCollection);
        }

        // GET: CardCollections/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            CardCollection cardCollection = db.CardCollection.Find(id);
            if (cardCollection == null)
            {
                return HttpNotFound();
            }
            ViewBag.CardID = new SelectList(db.CardDetails, "CardID", "CardName", cardCollection.CardID);
            ViewBag.collectorID = new SelectList(db.Collections, "collectorID", "UserID", cardCollection.collectorID);
            return View(cardCollection);
        }

        public ActionResult EditTrades(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            CardCollection cardCollection = db.CardCollection.Find(id);
            if (cardCollection == null)
            {
                return HttpNotFound();
            }
            ViewBag.CardID = new SelectList(db.CardDetails, "CardID", "CardName", cardCollection.CardID);
            ViewBag.collectorID = new SelectList(db.Collections, "collectorID", "UserID", cardCollection.collectorID);
            return View(cardCollection);
        }

        public ActionResult EditWants(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

HoardSorter/HoardSorter/Views/CardCollections/CancelTrade.cshtml
@model HoardSorter.Models.CardCollection

@{
    ViewBag.Title = "CancelTrade";
}

<h2>Cancel Trade</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.CardCollectionID)

        <div class="form-group">
            @Html.LabelFor(model => model.CardID, "CardID", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <h4>
                    @Html.DisplayFor(model => model.CardDetails.CardName)
                </h4>
                @Html.HiddenFor(model => model.CardID)
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-10">
                @Html.HiddenFor(model => model.ToTrade)
                @Html.ValidationMessageFor(model => model.ToTrade, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-10">
                @Html.HiddenFor(model => model.OwnedQty)
                @Html.ValidationMessageFor(model => model.OwnedQty, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-10">
                @Html.HiddenFor(model => model.TradeQty)
                @Html.ValidationMessageFor(model => model.TradeQty, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Cancel Trade" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to MyTrades", "MyTrades")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

HoardSorter/HoardSorter/Views/CardCollections/CompleteTrade.cshtml
@model HoardSorter.Models.CardCollection

@{
    ViewBag.Title = "CompleteTrade";
}

<h2>Complete Trade</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.CardCollectionID)

        <div class="form-group">
            @Html.LabelFor(model => model.CardID, "CardID", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <h4>
                    @Html.DisplayFor(model => model.CardDetails.CardName)
                </h4>
                @Html.HiddenFor(model => model.CardID)
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-10">
                @Html.HiddenFor(model => model.ToTrade)
                @Html.ValidationMessageFor(model => model.ToTrade, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-10">
                @Html.HiddenFor(model => model.OwnedQty)
                @Html.ValidationMessageFor(model => model.OwnedQty, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-10">
                @Html.HiddenFor(model => model.TradeQty)
                @Html.ValidationMessageFor(model => model.TradeQty, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                Warning: Completing a trade will remove the cards from your collection!
                <br />
                <input type="submit" value="Complete Trade" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to MyTrades", "MyTrades")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

HoardSorter/HoardSorter/Views/CardCollections/Create.cshtml
@model HoardSorter.Models.CardCollection

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>CardCollection</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.CardID, "CardID", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("CardID", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.CardID, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.OwnedQty, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.OwnedQty, new { htmlAttributes = new { @class = "form-control", @min = "0", @max = "99" } })
                @Html.ValidationMessageFor(model => model.OwnedQty, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Add Card" class="btn btn-default" />
            </div>
        </div>
    </div>
}

@ViewBag.Error
<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

HoardSorter/HoardSorter/Views/CardCollections/CreateTrade.cshtml
@model IEnumerable<HoardSorter.Models.CardCollection>

@{
    ViewBag.Title = "Create Trade";
}

<h2>Create Trade</h2>


<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.CardDetails.CardName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.OwnedQty)
        </th>

        <th></th>
    </tr>

    @foreach (var item in Model)
    {
    <tr>
        @if (item.OwnedQty > 0)
        {
            <td>
                @Html.DisplayFor(modelItem => item.CardDetails.CardName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.OwnedQty)
            </td>
            <td>
                @Html.ActionLink("Add to Trades", "EditTrades", new { id = item.CardCollectionID })
            </td>
        }
    </tr>
    }

</table>

<div>
    @Html.ActionLink("Back to MyTrades", "MyTrades")
</div>

HoardSorter/HoardSorter/Views/CardCollections/CreateWant.cshtml
@model HoardSorter.Models.CardCollection

@{
    ViewBag.Title = "Create Want";
}

<h2>Add Want</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.CardID, "CardID", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("CardID", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.CardID, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Wanted, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Wanted, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.OwnedQty, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.WantQty, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.WantQty, new { htmlAttributes = new { @class = "form-control", @min = "0", @max = "99" } })
                @Html.ValidationMessageFor(model => model.OwnedQty, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Add to MyWants" class="btn btn-default" />
            </div>
        </div>
    </div>

}
@ViewBag.Error

<div>
    @Html.ActionLink("Back to MyWants", "MyWants")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

HoardSorter/HoardSorter/Views/CardCollections/Delete.cshtml
@model HoardSorter.Models.CardCollection

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>CardCollection</h4>
    <hr />
    <dl class="dl-horizontal">

        <dt>
            @Html.DisplayNameFor(model => model.CardDetails.CardName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CardDetails.CardName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.OwnedQty)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.OwnedQty)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

HoardSorter/HoardSorter/Views/CardCollections/DeleteWant.cshtml
@model HoardSorter.Models.CardCollection

@{
    ViewBag.Title = "DeleteWant";
}

<h2>Delete Want</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.CardCollectionID)

        <div class="form-group">
            @Html.LabelFor(model => model.CardID, "CardID", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <h4>
                    @Html.DisplayFor(model => model.CardDetails.CardName)
                </h4>
                @Html.HiddenFor(model => model.CardID)
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-10">
                @Html.HiddenFor(model => model.Wanted)
                @Html.ValidationMessageFor(model => model.Wanted, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-10">
                @Html.HiddenFor(model => model.WantQty)
                @Html.ValidationMessageFor(model => model.WantQty, "", new { @class = "text-danger" })
            </div>
        </div>


        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Delete Want" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to MyWants", "MyWants")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

HoardSorter/HoardSorter/Views/CardCollections/Edit.cshtml
@model HoardSorter.Models.CardCollection

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
<div class="form-horizontal">
    <h4>CardCollection</h4>
    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    @Html.HiddenFor(model => model.CardCollectionID)

    <div class="form-group">

        <div class="col-md-10">
            @Html.HiddenFor(model => model.collectorID)
            @Html.ValidationMessageFor(model => model.collectorID, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.CardID, "CardID", htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.DropDownList("CardID", null, htmlAttributes: new { @class = "form-control" })
            @Html.ValidationMessageFor(model => model.CardID, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.OwnedQty, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.OwnedQty, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.OwnedQty, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        <div class="col-md-10">
            @Html.HiddenFor(model => model.TradeQty)
            @Html.ValidationMessageFor(model => model.TradeQty, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        <div class="col-md-10">
            @Html.HiddenFor(model => model.ToTrade)
            @Html.ValidationMessageFor(model => model.ToTrade, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Save" class="btn btn-default" />
        </div>
    </div>
</div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

HoardSorter/HoardSorter/Views/CardCollections/EditTrades.cshtml
@model HoardSorter.Models.CardCollection

@{
    ViewBag.Title = "EditTrades";
}

<h2>Edit MyTrades</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

<div class="form-horizontal">
    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    @Html.HiddenFor(model => model.CardCollectionID)

    <div class="form-group">
        @Html.LabelFor(model => model.CardDetails.CardName, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            <h4>
                @Html.DisplayFor(model => model.CardDetails.CardName)
            </h4>
            @Html.HiddenFor(model => model.CardID)
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.ToTrade, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            <div class="checkbox">
                @Html.EditorFor(model => model.ToTrade)
                @Html.ValidationMessageFor(model => model.ToTrade, "", new { @class = "text-danger" })
            </div>
        </div>
    </div>

    <div class="form-group">
        <div class="col-md-10">
            @Html.HiddenFor(model => model.OwnedQty)
            @Html.ValidationMessageFor(model => model.OwnedQty, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.TradeQty, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.TradeQty, new { htmlAttributes = new { @class = "form-control", @min = "0", @max = Model.OwnedQty } })
            @Html.ValidationMessageFor(model => model.TradeQty, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Save" class="btn btn-default" />
        </div>
    </div>
</div>
}

<div>
    @Html.ActionLink("Back to MyTrades", "MyTrades") |
    @Html.ActionLink("Back to Create Trade", "CreateTrade")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

HoardSorter/HoardSorter/Views/CardCollections/Search.cshtml
@model HoardSorter.Models.CardCollection

@{
    ViewBag.Title = "Search";
}

<h2>Global Search</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.CardID, "CardID", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("CardID", null, htmlAttributes: new { @class = "form-control" })
                <br />
                <input type="submit" value="Search" class="btn btn-default" />
            </div>
        </div>


        @*<div class="form-group">
                <div class="col-md-offset-2 col-md-10">

                    <input type="button" value="Search" onclick="location.href='@Url.Action("SearchResults", "CardCollections")'" />
                </div>
            </div>*@


    </div>
    <div>
        @Html.ActionLink("Back to MyWants", "MyWants")
    </div>
}